server:
  session:
    persistent: true
    timeout: 7200

spring:
  application:
    name: blog

  profiles:
    active: development

  jpa:
    database: postgresql
    show-sql: true

    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

  # Note: do not save password in git tracked files
  datasource:
    url: 'jdbc:postgresql://localhost/blog'

  session:
    # https://github.com/spring-projects/spring-session/blob/master/docs/src/docs/asciidoc/guides/boot-redis.adoc
    store-type: redis
    redis:
      namespace: ${spring.application.name}

  freemarker:
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    allowSessionOverride: true

  http:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: info
    org.hibernate: info

management:
  security:
    enabled: true
    roles: ADMIN

assets:
  broccoli:
    enabled: false
    host: localhost
    port: 4200

blog:
  title: "bianjp's Blog"

uploads:
  storage-dir: uploads
