spring:
  application:
    name: blog

  profiles:
    active: development,local

  jpa:
    database: postgresql
    show-sql: true

    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

#  # save in application-local.yml to avoid occasionally commit password into repository
#  datasource:
#    url: 'jdbc:postgresql://localhost/blog'
#    username:
#    password:

  redis:
    database: 0
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}

  session:
    store-type: redis

  freemarker:
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    allowSessionOverride: true

logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: info
    org.hibernate: info
  file: log/app.log

assets:
  development: true
  upstream: http://127.0.0.1:4200/

blog:
  title: "bianjp's Blog"
