spring:
  datasource:
    url: 'jdbc:postgresql://localhost/blog_development'

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

assets:
  cdn:
    enabled: false

  broccoli:
    enabled: true

blog:
  disqus:
    enabled: false
