spring:
  application:
    name: blog

  profiles:
    active: development,local

  jpa:
    database: postgresql
    show-sql: true

    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy

#  # save in application-local.yml to avoid occasionally commit password into repository
#  datasource:
#    url: 'jdbc:postgresql://localhost/blog'
#    username:
#    password:

  redis:
    database: 0
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}

  session:
    store-type: redis

  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    allowSessionOverride: true
