server:
  session:
    persistent: true
    timeout: 7200

spring:
  application:
    name: blog

  profiles:
    active: development,local

  jpa:
    database: postgresql
    show-sql: true

    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

#  # save in application-local.yml to avoid occasionally commit password into repository
#  datasource:
#    url: 'jdbc:postgresql://localhost/blog'
#    username:
#    password:

  redis:
    database: 0
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}

  session:
    # https://github.com/spring-projects/spring-session/blob/master/docs/src/docs/asciidoc/guides/boot-redis.adoc
    store-type: redis
    redis:
      namespace: ${spring.application.name}

  freemarker:
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    allowSessionOverride: true

  http:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: info
    org.hibernate: info
  file: log/app.log

management:
  security:
    enabled: true
    roles: ADMIN

assets:
  development: true
  upstream: http://127.0.0.1:4200/

blog:
  title: "bianjp's Blog"

uploads:
  storage-dir: uploads
